# Copyright 2019 Samsung Electronics Co., Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Default values for octavia.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

---
network:
  api:
    ingress:
      public: true
      classes:
        namespace: "nginx"
        cluster: "nginx"
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /
    external_policy_local: false
    node_port:
      enabled: false
      port: 30826


conf:
  octavia:
    DEFAULT:
      log_config_append: /etc/octavia/logging.conf
    api_settings:
      api_handler: queue_producer
      bind_host: 0.0.0.0
    controller_worker:
      amp_boot_network_list: 372f5ee6-f259-4885-ab37-c8035c6434fd
      workers: 2
      amp_ssh_key_name: null
    certificates:
      insecure: true


endpoints:
  cluster_domain_suffix: cluster.local
  identity:
    name: keystone
    auth:
      admin:
        region_name: RegionOne
        username: admin
        password: JcNvMAyVVka5eGwG
        project_name: admin
        user_domain_name: default
        project_domain_name: default
      octavia:
        role: admin
        region_name: RegionOne
        username: octavia
        password: password
        project_name: service
        user_domain_name: service
        project_domain_name: service
      test:
        role: admin
        region_name: RegionOne
        username: test
        password: password
        project_name: test
        user_domain_name: service
        project_domain_name: service
    hosts:
      default: keystone-api
      internal: keystone-api
    host_fqdn_override:
      public:
        host: iam.cloud.dev.yogiyo.io
    path:
      default: /v3
    scheme:
      default: 'http'
    port:
      api:
        default: 5000
        internal: 5000
        public: 80
  load_balancer:
    name: octavia
    hosts:
      default: octavia-api
    host_fqdn_override:
      public:
        host: lb.cloud.dev.yogiyo.io
    path:
      default: null
    scheme:
      default: http
    port:
      api:
        default: 9876
        public: 80
  oslo_db:
    auth:
      admin:
        username: root
        password: lgwXHkx6ZbK04RFFoE+JyQ==
      octavia:
        username: octavia
        password: 3zAijpfxACv2nscNfjdf3==
    hosts:
      default: mariadb-server
    path: /octavia
    scheme: mysql+pymysql
    port:
      mysql:
        default: 3306
  oslo_messaging:
    auth:
      admin:
        username: rabbitmq
        password: password
      octavia:
        username: octavia
        password: password
    statefulset:
      replicas: 4
      name: openstack-rabbitmq-rabbitmq
    path: /octavia
    scheme: rabbit
    port:
      amqp:
        default: 5672
      http:
        default: 15672
  network:
    name: neutron
    hosts:
      default: neutron-server
    host_fqdn_override:
      public:
        host: network.cloud.dev.yogiyo.io

pod:
  replicas:
    api: 1
    worker: 1
    housekeeping: 1


images:
  tags:
    octavia_db_sync: docker.io/loci/octavia:master-ubuntu
    db_drop: docker.io/openstackhelm/heat:ocata
    rabbit_init: docker.io/rabbitmq:3.7-management
    ks_user: docker.io/openstackhelm/heat:ocata
    ks_service: docker.io/openstackhelm/heat:ocata
    ks_endpoints: docker.io/openstackhelm/heat:ocata
    dep_check: quay.io/airshipit/kubernetes-entrypoint:v1.0.0
    image_repo_sync: docker.io/docker:17.07.0
    octavia_api: docker.io/loci/octavia:master-ubuntu
    octavia_worker: docker.io/loci/octavia:master-ubuntu
    octavia_housekeeping: docker.io/loci/octavia:master-ubuntu
    octavia_health_manager: docker.io/loci/octavia:master-ubuntu
    octavia_health_manager_init: docker.io/kolla/ubuntu-source-octavia-health-manager:rocky
    openvswitch_vswitchd: docker.io/kolla/centos-source-openvswitch-vswitchd:rocky