# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Default values for designate.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

---
release_group: null


bootstrap:
  enabled: true


pod:
  replicas:
    api: 1
    central: 1
    mdns: 4
    producer: 1
    sink: 1
    worker: 1
  mounts:
    designate_bootstrap:
      designate_bootstrap:
        volumeMounts:
        volumes:
      init_container: null
network:
  api:
    ingress:
      public: true
      classes:
        namespace: "nginx"
        cluster: "nginx"
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /
    external_policy_local: false
    node_port:
      enabled: false
      port: 9001
  mdns:
    name: "designate-mdns"
    proto: "http"
    external_policy_local: false
    node_port:
      enabled: true
      port: 5354

conf:
  pools:
    - name: default
      # The name is immutable. There will be no option to change the name after
      # creation and the only way will to change it will be to delete it
      # (and all zones associated with it) and recreate it.
      description: Default Pool
      attributes: {}
      # List out the NS records for zones hosted within this pool
      # This should be a record that is created outside of designate, that
      # points to the public IP of the controller node.
      ns_records:
        - hostname: ns1.openstack.devops.wesang.com.
          priority: 1
        - hostname: ns2.openstack.devops.wesang.com.
          priority: 1

      # List out the nameservers for this pool. These are the actual DNS servers.
      # We use these to verify changes have propagated to all nameservers.
      nameservers:
        - host: 10.0.155.250
          port: 53
          
      # List out the targets for this pool. For BIND there will be one
      # entry for each BIND server, as we have to run rndc command on each server
      targets:
        - type: pdns4
          description: PowerDNS Server

          # List out the designate-mdns servers from which PowerDNS servers should
          # request zone transfers (AXFRs) from.
          # This should be the IP of the controller node.
          # If you have multiple controllers you can add multiple masters
          # by running designate-mdns on them, and adding them here.
          masters:
            - host: 10.0.155.221
              port: 30163
            - host: 10.0.155.222
              port: 30163
            - host: 10.0.155.223
              port: 30163
            - host: 10.0.155.224
              port: 30163
              
          # PowerDNS Configuration options
          options:
            host: 10.0.155.250
            port: 53
            api_endpoint: http://10.0.155.250:8081
            api_token: Devops01

endpoints:
  cluster_domain_suffix: cluster.local
  identity:
    name: keystone
    auth:
      admin:
        region_name: RegionOne
        username: admin
        password: JcNvMAyVVka5eGwG
        project_name: admin
        user_domain_name: default
        project_domain_name: default
      designate:
        role: admin
        region_name: RegionOne
        username: designate
        password: dXx22dyVzca3ex1c
        project_name: service
        user_domain_name: service
        project_domain_name: service
      test:
        role: admin
        region_name: RegionOne
        username: designate-test
        password: password
        project_name: test
        user_domain_name: service
        project_domain_name: service
    hosts:
      default: keystone-api
      internal: keystone-api

    host_fqdn_override:
      public:
        host: iam.cloud.dev.yogiyo.io
    path:
      default: /v3
    scheme:
      default: http
      internal: http
      public: http
    port:
      api:
        default: 5000
        internal: 5000
        public: 80
  dns:
    name: designate
    hosts:
      default: designate-api
    host_fqdn_override:
      public:
        host: dns.cloud.dev.yogiyo.io 
    path:
      default: /
    scheme:
      default: 'http'
    port:
      api:
        default: 9001
        public: 80
  mdns:
    name: minidns
    hosts:
      default: minidns
    host_fqdn_override:
      public: 
        host: designate-mdns
    path:
      default: null
    scheme:
      default: 'tcp'
    port:
      ipc:
        default: 5354
  oslo_db:
    auth:
      admin:
        username: root
        password: lgwXHkx6ZbK04RFFoE+JyQ==
      designate:
        username: designate
        password: kgwZ1d16dB1d4Racoa+J1d==
    hosts:
      default: mariadb-server
    path: /designate
    scheme: mysql+pymysql
    port:
      mysql:
        default: 3306
  oslo_cache:
    hosts:
      default: memcached
    host_fqdn_override:
      default: null
    port:
      memcache:
        default: 11211
    auth:
      # NOTE: this is used to define the value for keystone
      # authtoken cache encryption key, if not set it will be populated
      # automatically with a random value, but to take advantage of
      # this feature all services should be set to use the same key,
      # and memcache service.
      memcache_secret_key: null
  oslo_messaging:
    statefulset:
      replicas: 4
      name: openstack-rabbitmq-rabbitmq
  powerdns:
    auth:
      service:
        token: devops01
    host_fqdn_override:
      public:
        host: pdns.cloud.dev.yogiyo.io
    port:
      powerdns_api:
        default: 8081
      powerdns:
        default: 53

manifests:
  configmap_bin: true
  configmap_etc: true
  deployment_api: true
  deployment_central: true
  deployment_worker: true
  deployment_producer: true
  deployment_mdns: true
  deployment_sink: false
  ingress_api: true
  job_bootstrap: true
  job_db_init: true
  job_db_sync: true
  job_ks_endpoints: true
  job_ks_service: true
  job_ks_user: true
  job_rabbit_init: true
  pdb_api: true
  pdb_producer: true
  pdb_central: true
  pdb_worker: true
  pdb_mdns: true
  pdb_sink: false
  secret_db: true
  secret_ingress_tls: true
  secret_keystone: true
  secret_rabbitmq: true
  secret_registry: true
  service_api: true
  service_mdns: true
  service_ingress_api: true
...
