# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Default values for glance.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

# radosgw, rbd, swift or pvc
---
storage: pvc


helm3_hook: false

network:
  api:
    ingress:
      public: true
      classes:
        namespace: "nginx"
        cluster: "nginx"
      annotations:
        # cert-manager.io/cluster-issuer: letsencrypt-prod
        nginx.ingress.kubernetes.io/rewrite-target: /
        nginx.ingress.kubernetes.io/proxy-body-size: "0"

volume:
  class_name: ceph-rbd
  size: 1000Gi

# Names of secrets used by bootstrap and environmental checks
# secrets:
#   tls:
#     image:
#       api:
#         public: glance-tls-public

# typically overridden by environmental
# values, but should include all endpoints
# required by this chart
endpoints:
  identity:
    auth:
      admin:
        region_name: RegionOne
        username: admin
        password: JcNvMAyVVka5eGwG
        project_name: admin
        user_domain_name: default
        project_domain_name: default
      glance:
        role: admin
        region_name: RegionOne
        username: glance
        password: QYoYqLUSyfIdeDfs
        project_name: service
        user_domain_name: service
        project_domain_name: service
      test:
        role: admin
        region_name: RegionOne
        username: glance-test
        password: password
        project_name: test
        user_domain_name: service
        project_domain_name: service
    host_fqdn_override:
      default: keystone-api
    path:
      default: /v3
    scheme:
      default: http
      public: http
    port:
      api:
        default: 5000
        internal: 5000
  image:
    name: glance
    host_fqdn_override:
      public:
        host: image.cloud.dev.yogiyo.io
        tls:
          crt: tmp
          key: tmp
    scheme:
      default: http
      service: http
      public: http
    port:
      api:
        default: 9292
        public: 80
  oslo_db:
    auth:
      admin:
        username: root
        password: lgwXHkx6ZbK04RFFoE+JyQ==
        secret:
          tls:
            internal: mariadb-tls-direct
      glance:
        username: glance
        password: 0l/m3vWQKS9S4J+Z99R5sg==
    host_fqdn_override:
      default: mariadb-server
    path: /glance
    scheme: mysql+pymysql
    port:
      mysql:
        default: 3306
  oslo_cache:
    auth:
      # NOTE(portdirect): this is used to define the value for keystone
      # authtoken cache encryption key, if not set it will be populated
      # automatically with a random value, but to take advantage of
      # this feature all services should be set to use the same key,
      # and memcache service.
      memcache_secret_key: null
    hosts:
      default: memcached
    host_fqdn_override:
      default: null
    port:
      memcache:
        default: 11211
  oslo_messaging:
    auth:
      admin:
        username: rabbitmq
        password: password
        secret:
          tls:
            internal: rabbitmq-tls-direct
      glance:
        username: glance
        password: password
    statefulset:
      replicas: 4
      name: openstack-rabbitmq-rabbitmq
    hosts:
      default: rabbitmq
    host_fqdn_override:
      default: null
    path: /glance
    scheme: rabbit
    port:
      amqp:
        default: 5672
      http:
        default: 15672
pod:
  replicas:
    api: 1
